name: market_analytics
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.2
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - idna=3.3
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=6.9.1
  - ipympl=0.8.7
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.1.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - plotly=5.6.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1.2
  - requests=2.27.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.38.0
  - stack_data=0.2.0
  - tabulate=0.8.9
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - ciso8601==2.2.0
    - ftx==1.2.0
    - gevent==21.12.0
    - greenlet==1.1.2
    - kaleido==0.2.1
    - pandas-ta==0.3.14b0
    - pycoingecko==2.2.0
    - zope-event==4.5.0
    - zope-interface==5.4.0
