name: market_analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - blas-devel=3.9.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.5
  - contourpy=1.0.5
  - cryptography=38.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - fftw=3.3.9
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - ipykernel=6.15.2
  - ipympl=0.8.7
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jupyter_client=7.4.7
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nomkl=3.0
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openblas=0.3.20
  - openblas-devel=0.3.20
  - openjpeg=2.3.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.2
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - plotly=5.9.0
  - portaudio=19.6.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-sounddevice=0.4.1
  - python_abi=3.10
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.28.1
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=65.5.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.3
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tabulate=0.8.10
  - tenacity=8.0.1
  - terminado=0.13.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=14.0.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.8
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.1
      - aiosignal==1.2.0
      - async-timeout==4.0.2
      - asyncio==3.4.3
      - base58==2.1.1
      - bitarray==1.2.2
      - bitfinex-api-py==2.0.1
      - brotli==1.0.9
      - ciso8601==2.2.0
      - click==8.1.3
      - cvxpy==1.2.0
      - cytoolz==0.11.2
      - dash==2.5.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - ecos==2.0.10
      - eth-abi==2.1.1
      - eth-account==0.5.7
      - eth-hash==0.3.2
      - eth-keyfile==0.5.1
      - eth-keys==0.3.4
      - eth-rlp==0.2.1
      - eth-typing==2.3.0
      - eth-utils==1.10.0
      - flask==2.1.2
      - flask-compress==1.12
      - frozenlist==1.3.0
      - ftx==1.2.0
      - future==0.18.2
      - gevent==21.12.0
      - greenlet==1.1.2
      - hexbytes==0.2.2
      - ipfshttpclient==0.8.0a2
      - itsdangerous==2.1.2
      - joblib==1.1.0
      - jsonschema==3.2.0
      - kaleido==0.2.1
      - lru-dict==1.1.7
      - lxml==4.8.0
      - multiaddr==0.0.9
      - multidict==6.0.2
      - multipledispatch==0.6.0
      - netaddr==0.8.0
      - osqp==0.6.2.post5
      - pandas-datareader==0.10.0
      - pandas-ta==0.3.14b0
      - parsimonious==0.8.1
      - protobuf==3.19.4
      - pybind11==2.9.2
      - pycoingecko==2.2.0
      - pycryptodome==3.14.1
      - pyee==8.2.2
      - pyportfolioopt==1.5.2
      - qdldl==0.1.5.post2
      - rlp==2.0.1
      - scikit-learn==1.0.2
      - scs==3.2.0
      - seaborn==0.11.2
      - threadpoolctl==3.1.0
      - toolz==0.11.2
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchvision==0.12.0
      - typing-extensions==4.2.0
      - varint==1.0.2
      - web3==5.28.0
      - websockets==9.1
      - werkzeug==2.1.2
      - yarl==1.7.2
      - zope-event==4.5.0
      - zope-interface==5.4.0
