name: market_analytics
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - anyio=3.4.0
  - appnope=0.1.2
  - argon2-cffi=21.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.5.30
  - cffi=1.15.0
  - charset-normalizer=2.0.9
  - cryptography=36.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fonttools=4.28.5
  - freetype=2.10.4
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - ipykernel=6.6.0
  - ipympl=0.8.4
  - ipython=7.30.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.3.2
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.13.1
  - jupyterlab=3.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.1
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.3.4
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - notebook=6.4.6
  - numpy=1.21.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - plotly=4.14.3
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.1
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - retrying=1.3.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - pycoingecko==2.2.0
